"""price int -> float

Revision ID: 263e755bd6fa
Revises: 6fabc3927235
Create Date: 2022-11-05 17:45:31.949413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '263e755bd6fa'
down_revision = '6fabc3927235'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
