"""sn mapping info

Revision ID: 3ed2c5a725e8
Revises: 79b5fb996614
Create Date: 2022-11-06 16:25:23.095529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ed2c5a725e8'
down_revision = '79b5fb996614'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
