"""add mapping info columns in tsn and spgz

Revision ID: 4d1ce577d2df
Revises: 62d3d9814ba0
Create Date: 2022-11-04 17:26:12.399679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d1ce577d2df'
down_revision = '62d3d9814ba0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spgz', sa.Column('mapping_info', sa.String(), nullable=True))
    op.add_column('tsn', sa.Column('tsn_mapping_info', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tsn', 'tsn_mapping_info')
    op.drop_column('spgz', 'mapping_info')
    # ### end Alembic commands ###
