"""first migration

Revision ID: 6df9d3b21060
Revises: 
Create Date: 2022-11-02 16:57:39.808336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6df9d3b21060'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpgz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_kpgz_id'), 'kpgz', ['id'], unique=False)
    op.create_table('tsn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_tsn_id'), 'tsn', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('spgz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('okpd', sa.String(), nullable=True),
    sa.Column('okpd2', sa.String(), nullable=True),
    sa.Column('uom', sa.String(), nullable=True),
    sa.Column('kpgz_piece_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kpgz_piece_id'], ['kpgz.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_id')
    )
    op.create_index(op.f('ix_spgz_id'), 'spgz', ['id'], unique=False)
    op.create_table('hypothesis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('tsn_piece_id', sa.Integer(), nullable=True),
    sa.Column('spgz_piece_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['spgz_piece_id'], ['spgz.id'], ),
    sa.ForeignKeyConstraint(['tsn_piece_id'], ['tsn.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hypothesis_id'), 'hypothesis', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hypothesis_id'), table_name='hypothesis')
    op.drop_table('hypothesis')
    op.drop_index(op.f('ix_spgz_id'), table_name='spgz')
    op.drop_table('spgz')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tsn_id'), table_name='tsn')
    op.drop_table('tsn')
    op.drop_index(op.f('ix_kpgz_id'), table_name='kpgz')
    op.drop_table('kpgz')
    # ### end Alembic commands ###
