"""sn mapping info

Revision ID: 79b5fb996614
Revises: 9ffc8ad630ba
Create Date: 2022-11-06 14:59:17.726641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79b5fb996614'
down_revision = '9ffc8ad630ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sn', sa.Column('sn_mapping_info', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sn', 'sn_mapping_info')
    # ### end Alembic commands ###
