"""add counter to hypothesises

Revision ID: 9e21547717a0
Revises: 4d1ce577d2df
Create Date: 2022-11-04 23:03:26.013942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e21547717a0'
down_revision = '4d1ce577d2df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sn_hypothesis', sa.Column('usage_counter', sa.Integer(), nullable=True))
    op.add_column('tsn_hypothesis', sa.Column('usage_counter', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tsn_hypothesis', 'usage_counter')
    op.drop_column('sn_hypothesis', 'usage_counter')
    # ### end Alembic commands ###
