"""probability and spgz_defined

Revision ID: 9ffc8ad630ba
Revises: 263e755bd6fa
Create Date: 2022-11-06 13:54:20.506511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ffc8ad630ba'
down_revision = '263e755bd6fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sn', sa.Column('spgz_defined', sa.Boolean(), nullable=True))
    op.add_column('sn_hypothesis', sa.Column('probability', sa.Float(), nullable=True))
    op.add_column('tsn', sa.Column('spgz_defined', sa.Boolean(), nullable=True))
    op.add_column('tsn_hypothesis', sa.Column('probability', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tsn_hypothesis', 'probability')
    op.drop_column('tsn', 'spgz_defined')
    op.drop_column('sn_hypothesis', 'probability')
    op.drop_column('sn', 'spgz_defined')
    # ### end Alembic commands ###
