"""add uom to tsn migration

Revision ID: d95816664790
Revises: 6df9d3b21060
Create Date: 2022-11-03 13:32:54.071490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd95816664790'
down_revision = '6df9d3b21060'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tsn', sa.Column('uom', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tsn', 'uom')
    # ### end Alembic commands ###
